### PR TITLE
Implement multispecificity

### PR DESCRIPTION
**Pull request by EmilyTLin**

### CODE REVIEW

**Review by borcuttjahns — APPROVED** [review]
Plenty here involving code that could be given a little love in the future, but I don't think there's anything wrong with what is here in terms of accuracy/validity!

**Comment by borcuttjahns** [comment]
Although actually we should fix the fact that this doesn't build and fails the tests! I'm guessing it has to do with the inputs to the binding functions!

**Review by borcuttjahns — APPROVED** [review]
Looks even better!

**Comment by EmilyTLin** [comment]
Test doesn't work because Codecov seems to be down (it fails on the main branch as well)
Build cancelled because it takes a long time, but I ran test versions to build/generate all the figures on VSC and they all work, so there shouldn't be any problems

**Pull request merged**
